services:
  api:
    container_name: api
    image: frreimon/api:2.5
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app
    env_file:
      - .env
  
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    env_file:
      - .env